server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

project:
  access.log:
    enabled: true
    request-header: true
    request-param: true
    request-body: true
    response-header: true
    response-body: true
    request-body-length: 1000
    response-body-length: 1000
    request-header-names:
    response-header-names:
    exclude-path-patterns:
  datasources:
    enabled: true
    datasource-item-list:
      - datasource-name: "conditioncoupon-ds"
        enabled: true
        driver-class-name: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
        jdbc-url: "jdbc:log4jdbc:mariadb://10.90.1.220:3306/conditioncoupon_db?useSSL=false&allowMultiQueries=true"
        username: "conditioncoupon"
        password: "conditioncoupon!@34"
        maximum-pool-size: 5
        lazy-connection: true
      - datasource-name: "lmmdev11-ds"
        enabled: true
        driver-class-name: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
        jdbc-url: "jdbc:log4jdbc:oracle:thin:@devdb11.lemonm.kr:1521:lmmdev11"
        username: "daelim"
        password: "daelimroqkf1"
        maximum-pool-size: 5
        lazy-connection: true
  mybatis:
    enabled: true
    mybatis-item-list:
      - enabled: true
        datasource-name: "conditioncoupon-ds"
        sql-session-template-name: "conditioncoupon-template"
        config-location: "classpath:mybatis/mybatis-config.xml"
        mapper-locations:
          - "classpath*:mapper/conditioncoupon/**/*.xml"
        type-aliases-packages:
          - "com.project.cmn.http.persistence.conditioncoupon.model"
        mapper-package: "com.project.cmn.http.persistence.conditioncoupon.mapper"
      - enabled: true
        datasource-name: "lmmdev11-ds"
        sql-session-template-name: "lmmdev11-template"
        config-location: "classpath:mybatis/mybatis-config.xml"
        mapper-locations:
          - "classpath*:mapper/lmmdev11/**/*.xml"
        type-aliases-packages:
          - "com.project.cmn.http.persistence.lmmdev11.model"
        mapper-package: "com.project.cmn.http.persistence.lmmdev11.mapper"